[".OBJ"]
".metaid" = "140187322473920"

[".META".140187322473920]
".metatype" = "func"
".name" = "wrapper_"
".module" = "__main__"

[".META".140187322473920.".code"]
co_argcount = 1
co_posonlyargcount = 0
co_kwonlyargcount = 0
co_nlocals = 2
co_stacksize = 3
co_flags = 3
co_code = [ 135, 0, 102, 1, 100, 1, 100, 2, 132, 8, 125, 1, 124, 1, 83, 0,]
co_filename = "/home/staselko/Documents/lab2petuhon/sandbox.py"
co_name = "wrapper_"
co_firstlineno = 26
co_lnotab = [ 0, 1, 12, 3,]

[".META".140187322473920.".refs"]
".collection_type" = "tuple"
[[".META".140187322473920.".refs".".list"]]

[[".META".140187322473920.".refs".".list"]]

[[".META".140187322473920.".refs".".list"]]

[[".META".140187322473920.".refs".".list"]]
".list" = []
".collection_type" = "set"

[".META".140187322473920.".code".co_consts]
".list" = [ "None", "None", "wrapper_.<locals>.wrap",]
".collection_type" = "tuple"

[".META".140187322473920.".code".co_names]
".list" = []
".collection_type" = "tuple"

[".META".140187322473920.".code".co_varnames]
".list" = [ "func", "wrap",]
".collection_type" = "tuple"

[".META".140187322473920.".code".co_freevars]
".list" = []
".collection_type" = "tuple"

[".META".140187322473920.".code".co_cellvars]
".list" = [ "func",]
".collection_type" = "tuple"
